AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  python3.9

Resources:
  ScheduledEbayScrape:
    Type: AWS::Serverless::Function
    Properties:
      Description: A Lambda function that scrapes eBay Kleinanzeigen and classifies the postings.
      PackageType: Image
      Architectures:
        - x86_64
      # This property associates this Lambda function with a scheduled CloudWatch Event. For all available properties, see
      # https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#schedule
      # This example runs every hour.
      Events:
        CloudWatchEvent:
          Type: Schedule
          Properties:
            Schedule: rate(1 hour)
      MemorySize: 1024
      Timeout: 900000
      Environment:
        Variables:
          MODEL_URL:
          MODEL_API_KEY:
          BACKEND_URL:
          BACKEND_ADMIN_KEY:
          CHROME_BINARY_LOC: /var/task/headless-chromium
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./
      DockerTag: python3.9-v1
